<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeedbackSeeder extends Seeder
{
    public function run(): void
    {
        $feedbacks = [
            [
                'user_id' => 2, // User ID 2 from your DatabaseSeeder
                'rating' => 5,
                'message' => 'Absolutely brilliant tool for Islamic inheritance calculations. Highly recommended!',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Exceptional tool. Recommended to all family and friends.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(28),
                'updated_at' => now()->subDays(28),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Incredibly helpful for teaching Islamic inheritance concepts.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(25),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Helped our family settle inheritance peacefully.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(22),
                'updated_at' => now()->subDays(22),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Excellent for quick and accurate Islamic finance calculations.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(20),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Very good calculator with accurate results.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(18),
                'updated_at' => now()->subDays(18),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Best online faraid calculator I\'ve found.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(15),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Empowering tool for understanding inheritance rights.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(12),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Good calculator that follows Islamic principles.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Excellent resource for students and professionals.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Great tool for handling inheritance scenarios.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(6),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Saved us thousands in legal fees.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Solid calculator with accurate core calculations.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Helped me learn about Islamic inheritance laws.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Professional tool I use regularly in my law practice.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Helped distribute my late father\'s estate correctly.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Very reliable with accurate results.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(23),
                'updated_at' => now()->subHours(23),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Game-changer for Muslim families.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(20),
                'updated_at' => now()->subHours(20),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Recommend to all my clients for Islamic finance.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(18),
                'updated_at' => now()->subHours(18),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Great for learning about Islamic inheritance.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(15),
                'updated_at' => now()->subHours(15),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Exceeds all expectations. Impeccable accuracy.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Brought clarity to complex inheritance matters.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(10),
                'updated_at' => now()->subHours(10),
            ],
            [
                'user_id' => 2,
                'rating' => 4,
                'message' => 'Solid Islamic foundation with accurate results.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(8),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Resolved our family inheritance issue.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'user_id' => 2,
                'rating' => 5,
                'message' => 'Recommend to all community members.',
                'status' => 'approved',
                'is_visible' => true,
                'is_public' => true,
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
        ];

        // Insert feedback into database
        DB::table('feedback')->insert($feedbacks);

        $this->command->info('25 feedback entries added successfully!');
    }
}