<?php

require __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Calculation;
use App\Services\FamilyTreeService;
use Illuminate\Support\Facades\Log;

echo "Testing Family Tree Generation...\n\n";

// Create test calculation data
$calculationData = [
    'user_id' => 1,
    'deceased_name' => 'John Doe',
    'deceased_gender' => 'male',
    'date_of_death' => '2024-01-01',
    'marital_status' => 'married',
    'wife_count' => 1,
    'husband_count' => 0,
    'father_status' => 'alive',
    'mother_status' => 'alive',
    'son_count' => 2,
    'daughter_count' => 1,
    'total_assets' => 100000,
    'debts' => 5000,
    'funeral_costs' => 3000,
    'wasiyyah' => 10000,
    'net_assets' => 82000,
    'total_heirs' => 5,
    'calculation_hash' => Calculation::generateHash(),
    'heirs_data' => json_encode([
        'wife_count' => 1,
        'husband_count' => 0,
        'father_status' => 'alive',
        'mother_status' => 'alive',
        'son_count' => 2,
        'daughter_count' => 1,
    ]),
    'calculation_data' => json_encode([
        'distribution' => [
            ['heir' => 'Wife', 'relationship' => 'wife', 'share' => '1/8', 'amount' => 10250, 'fraction' => 0.125],
            ['heir' => 'Father', 'relationship' => 'father', 'share' => '1/6', 'amount' => 13666.67, 'fraction' => 0.1667],
            ['heir' => 'Mother', 'relationship' => 'mother', 'share' => '1/6', 'amount' => 13666.67, 'fraction' => 0.1667],
            ['heir' => 'Son 1', 'relationship' => 'son', 'share' => 'Residual', 'amount' => 22208.33, 'fraction' => 0.2708],
            ['heir' => 'Son 2', 'relationship' => 'son', 'share' => 'Residual', 'amount' => 22208.33, 'fraction' => 0.2708],
        ]
    ]),
];

echo "1. Testing Calculation model...\n";
try {
    $calculation = new Calculation($calculationData);
    $calculation->save();
    
    echo "✓ Calculation created successfully (ID: {$calculation->id})\n";
    echo "   Hash: {$calculation->calculation_hash}\n";
} catch (Exception $e) {
    echo "✗ Error creating calculation: " . $e->getMessage() . "\n";
    exit(1);
}

echo "\n2. Testing FamilyTreeService directly...\n";
try {
    $heirsData = [
        'wife_count' => 1,
        'husband_count' => 0,
        'father_status' => 'alive',
        'mother_status' => 'alive',
        'son_count' => 2,
        'daughter_count' => 1,
    ];
    
    $distribution = [
        ['heir' => 'Wife', 'relationship' => 'wife', 'share' => '1/8', 'amount' => 10250, 'fraction' => 0.125],
        ['heir' => 'Father', 'relationship' => 'father', 'share' => '1/6', 'amount' => 13666.67, 'fraction' => 0.1667],
        ['heir' => 'Mother', 'relationship' => 'mother', 'share' => '1/6', 'amount' => 13666.67, 'fraction' => 0.1667],
        ['heir' => 'Son 1', 'relationship' => 'son', 'share' => 'Residual', 'amount' => 22208.33, 'fraction' => 0.2708],
        ['heir' => 'Son 2', 'relationship' => 'son', 'share' => 'Residual', 'amount' => 22208.33, 'fraction' => 0.2708],
    ];
    
    $service = new FamilyTreeService(
        ['name' => 'John Doe', 'gender' => 'male'],
        $heirsData,
        $distribution
    );
    
    echo "✓ FamilyTreeService instance created\n";
    
    $filename = 'direct_test_' . time();
    $result = $service->generate($filename);
    
    if ($result) {
        echo "✓ Family tree generated: {$result}\n";
        
        // Extract path from URL
        $path = parse_url($result, PHP_URL_PATH);
        $storagePath = str_replace('/storage/', 'app/public/', $path);
        $fullPath = storage_path($storagePath);
        
        if (file_exists($fullPath)) {
            echo "✓ File exists: " . $fullPath . "\n";
            echo "  Size: " . filesize($fullPath) . " bytes\n";
            
            // Check content
            $content = file_get_contents($fullPath);
            if (strpos($result, '.svg') !== false) {
                if (strpos($content, '<svg') !== false) {
                    echo "✓ Valid SVG file\n";
                    
                    // Check for Graphviz output
                    if (strpos($content, 'Generated by graphviz') !== false) {
                        echo "✓ Generated by Graphviz\n";
                    }
                } else {
                    echo "✗ Invalid SVG - no SVG tag found\n";
                }
            } elseif (strpos($result, '.html') !== false) {
                if (strpos($content, '<!DOCTYPE') !== false) {
                    echo "✓ Valid HTML file\n";
                }
            }
        } else {
            echo "✗ File not found at expected location\n";
        }
    } else {
        echo "✗ Family tree generation failed\n";
    }
} catch (Exception $e) {
    echo "✗ Error: " . $e->getMessage() . "\n";
    echo "Trace: " . $e->getTraceAsString() . "\n";
}

echo "\n3. Testing through CalculationController flow...\n";
try {
    // Simulate the controller flow
    $calculation = Calculation::find($calculation->id);
    
    if ($calculation) {
        $calculationData = json_decode($calculation->calculation_data, true) ?? [];
        
        if (!empty($calculationData['distribution'])) {
            $heirsData = [
                'wife_count' => $calculation->wife_count ?? 0,
                'husband_count' => $calculation->husband_count ?? 0,
                'father_status' => $calculation->father_status ?? 'none',
                'mother_status' => $calculation->mother_status ?? 'none',
                'son_count' => $calculation->son_count ?? 0,
                'daughter_count' => $calculation->daughter_count ?? 0,
            ];
            
            $familyTreeService = new FamilyTreeService(
                [
                    'name' => $calculation->deceased_name,
                    'gender' => $calculation->deceased_gender
                ],
                $heirsData,
                $calculationData['distribution']
            );
            
            $filename = 'controller_test_' . $calculation->id . '_' . time();
            $familyTreeImage = $familyTreeService->generate($filename);
            
            if ($familyTreeImage) {
                echo "✓ Family tree generated via controller flow\n";
                echo "  URL: {$familyTreeImage}\n";
                
                // Update calculation
                $calculation->update([
                    'family_tree_image' => $familyTreeImage,
                    'tree_generated_at' => now()
                ]);
                
                echo "✓ Calculation updated with tree image\n";
                
                // Verify the update
                $updated = Calculation::find($calculation->id);
                if ($updated->family_tree_image) {
                    echo "✓ Tree image saved to database\n";
                    echo "  Image URL: " . $updated->getFamilyTreeUrl() . "\n";
                } else {
                    echo "✗ Tree image not saved to database\n";
                }
            } else {
                echo "✗ Failed to generate tree via controller flow\n";
            }
        } else {
            echo "✗ No distribution data found in calculation\n";
        }
    } else {
        echo "✗ Calculation not found\n";
    }
} catch (Exception $e) {
    echo "✗ Error: " . $e->getMessage() . "\n";
}

echo "\n4. Cleaning up test data...\n";
try {
    // Delete test calculations
    Calculation::where('deceased_name', 'John Doe')->delete();
    echo "✓ Test data cleaned up\n";
} catch (Exception $e) {
    echo "✗ Error cleaning up: " . $e->getMessage() . "\n";
}

echo "\nTest completed!\n";